project:
  type: website

website:
  title: "Case Study: Providing Pensions for the Poor"
  navbar: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"

editor: visual

